create table quiz (
    id bigint generated by default as identity (start with 1) primary key,
    question varchar(425),
    option1 varchar(225),
    option2 varchar(225),
    option3 varchar(225),
    option4 varchar(225),
    answer varchar(225),
    message varchar(225)
);